// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCArJbAeY3s5pEgJ977v3T8Pxg_PurehZE',
    appId: '1:544279218915:web:0c3764e2f94742eb71d3d6',
    messagingSenderId: '544279218915',
    projectId: 'basya-investama',
    authDomain: 'basya-investama.firebaseapp.com',
    storageBucket: 'basya-investama.firebasestorage.app',
    measurementId: 'G-S12MJXVDNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvASrvNkXnMqe-2mz9pGO3t7EEmqM9DE4',
    appId: '1:544279218915:android:3b19f3201d98c78b71d3d6',
    messagingSenderId: '544279218915',
    projectId: 'basya-investama',
    storageBucket: 'basya-investama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7Tn43vxoSFZdcqcDEVqDPhK73l_OtDw',
    appId: '1:544279218915:ios:8a34f5563b4f842871d3d6',
    messagingSenderId: '544279218915',
    projectId: 'basya-investama',
    storageBucket: 'basya-investama.firebasestorage.app',
    iosBundleId: 'com.example.basyaInvestama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7Tn43vxoSFZdcqcDEVqDPhK73l_OtDw',
    appId: '1:544279218915:ios:8a34f5563b4f842871d3d6',
    messagingSenderId: '544279218915',
    projectId: 'basya-investama',
    storageBucket: 'basya-investama.firebasestorage.app',
    iosBundleId: 'com.example.basyaInvestama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCArJbAeY3s5pEgJ977v3T8Pxg_PurehZE',
    appId: '1:544279218915:web:bce64bbd4842315271d3d6',
    messagingSenderId: '544279218915',
    projectId: 'basya-investama',
    authDomain: 'basya-investama.firebaseapp.com',
    storageBucket: 'basya-investama.firebasestorage.app',
    measurementId: 'G-2HD1G5G9YC',
  );
}
